language: c

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

sudo: false

env:
  - BUILD_TYPE=tiny
  - BUILD_TYPE=sigar-asm

os:
  - linux
  - osx

before_install:
  - git submodule update --init --recursive
  - git submodule update --recursive

script:
  - WITHOUT_AMALG=1 make ${BUILD_TYPE}
  - make test

jobs:
  include:
    - stage: deploy
      if: tag IS present
      os: linux
      env: []
      script:
        # fetch tags so that git describe works
        - git fetch -t --recurse-submodules=no
        - make linux-build
      services:
        - docker
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "luvi-tiny-Linux_x86_64"
          - "luvi-sigar-Linux_x86_64"
          - "luvi-tiny-Linux_i686"
          - "luvi-sigar-Linux_i686"
        overwrite: true
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      if: tag IS present
      os: osx
      env: []
      script:
        # fetch tags so that git describe works
        - git fetch --unshallow
        - make travis-publish
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "luvi-regular-Darwin_x86_64"
          - "luvi-tiny-Darwin_x86_64"
          - "luvi-src-$TRAVIS_TAG.tar.gz"
        overwrite: true
        skip_cleanup: true
        on:
          tags: true

